#!/usr/bin/env php
<?php
// Basic CLI actions for PHP Mini Framework

function createController($name)
{
    if (!file_exists("app/controllers/".$name.".php")) {
        $controllerFile = fopen("app/controllers/".$name.".php", "w") or die("Unable to open file!");
        $content = "";
        $content .= "<?php";
        $content .= "\n";
        $content .= "class ".$name." extends SiteController";
        $content .= "\n";
        $content .= "{";
        $content .= "\n";
        $content .= "    protected \$db;";
        $content .= "\n";
        $content .= "\n";
        $content .= "    public function __construct(\$db)";
        $content .= "\n";
        $content .= "    {";
        $content .= "\n";
        $content .= "        \$this->db = \$db;";
        $content .= "\n";
        $content .= "    }";
        $content .= "\n";
        $content .= "\n";
        $content .= "    public function index()";
        $content .= "\n";
        $content .= "    {";
        $content .= "\n";
        $content .= "    }";
        $content .= "\n";
        $content .= "}";
    
        // Write to the file
        fwrite($controllerFile, $content);
        fclose($controllerFile);
    
        // Output Success
        print_r("Controller: app/controllers/".$name.".php created!");
    } else {
        // Output Failure
        print_r("FAILED. app/controllers/".$name.".php already exists.");
    }
}

function createModel($name)
{
    if (!file_exists("app/models/".$name.".php")) {
        $modelFile = fopen("app/models/".$name.".php", "w") or die("Unable to open file!");
        $content = "";
        $content .= "<?php";
        $content .= "\n";
        $content .= "class ".$name;
        $content .= "\n";
        $content .= "{";
        $content .= "\n";
        $content .= "    protected \$db;";
        $content .= "\n";
        $content .= "\n";
        $content .= "    public function __construct(\$db)";
        $content .= "\n";
        $content .= "    {";
        $content .= "\n";
        $content .= "        \$this->db = \$db;";
        $content .= "\n";
        $content .= "    }";
        $content .= "\n";
        $content .= "\n";
        $content .= "    public function modelFunction()";
        $content .= "\n";
        $content .= "    {";
        $content .= "\n";
        $content .= "    }";
        $content .= "\n";
        $content .= "}";

        // Write to the file
        fwrite($modelFile, $content);
        fclose($modelFile);

        // Output Success
        print_r("Model: app/models/".$name.".php created!");
    } else {
        // Output Failure
        print_r("FAILED. app/models/".$name.".php already exists.");
    }
}

//print_r($argc); // number or arguments
//print_r($argv);
$command = $argv[1];

// Create a certain file type
if (strpos($command, 'create:') !== false && isset($argv[2])) {
    $commandParts = explode(':', $command);
    $makeThis = $commandParts[1];

    // Create a controller
    if ($makeThis == 'controller') {
        $controllerName = $argv[2];
        createController($controllerName);
    }

    // Create a model
    if ($makeThis == 'model') {
        $modelName = $argv[2];
        createModel($modelName);
    }

} else {
    print_r("Not a valid Mini Framework command.");
}

echo "\n";
die();