name: CI

on: [push]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -n --prefer-dist
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: PHPUnit Tests
          uses: php-actions/phpunit@master
          with:
            bootstrap: vendor/autoload.php
            configuration: phpunit.xml
            args: --coverage-text

